AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - '**/*.rake'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
