AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
  Max: 50
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 10